<div class="lightbox-single-image <?php echo $this->getCssClass()?>" <?php echo $this->getHsConfig();?>>
    <a href="<?php echo $this->getImage()?>" class="highslide" title="<?php echo $this->getTitle()?>">
        <img src="<?php echo $this->getThumbnailImage(); ?>"  alt="<?php echo $this->getTitle()?>" style="width: <?php echo $this->getThumbnailWidth()?>; height: <?php echo $this->getThumbnailHeight()?>;"/>
    </a>
</div>
