<?php
    $_helper = $this->helper('catalog/output');
    $products = $this->getProductCollection();
?>
<?php if($products && $products->count()) : ?>
    <h3 style="text-align: center;"><?php echo Mage::helper('soldtogether')->__('Customers who bought this product also commonly purchased the following combination of items') ?></h3>
    <table class="items" cellpadding="0" cellspacing="0" border="0">
        <tr style="text-align: center;">
        <?php foreach ($products as $_product) : ?>
                <td class="cell-content" style="max-width: 150px; padding: 15px; text-align: center; display: inline-block;">
                    <div class="product-image-wrapper">
                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                </div>
                <h3 class="product-name" style="text-align: center;">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                </h3>
                <?php echo $this->getPriceHtml($_product, true, '-related-customer') ?>
                </td>
        <?php endforeach; ?>
        </tr>
    </table>
<?php endif; ?>